apiVersion: apps/v1
kind: Deployment
metadata:
  name: facebook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: facebook
  template:
    metadata:
      labels:
        app: facebook
    spec:
      nodeSelector:
        agentpool: dev
      terminationGracePeriodSeconds: 0
      containers:
      - image: qaptum.azurecr.io/ingest-fb:a708ec38496fa21ec3d30a309a633eef7d0c1c5b
        name: facebook
        #command: ["sleep", "100000000"]
        command: ["./facebook.sh"]
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"        
      imagePullSecrets:
      - name: acr-secret

---

apiVersion: v1
kind: Service
metadata:
  name: facebook
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: facebook
    port: 8000
  selector:
    app: facebook
